"""REAL-server step definitions + integration teeth for the watcher engage's
finite runs connecting to the ONE shared per-container fabro server at the
address the engage BINDS == the address it EXPORTS as ``FABRO_SERVER``
(scenarios ab9b2be40558cfc2 message-driven + 33488b7e1657b7c7 startup-drain +
89e975a7a38fdcaf real-telemetry, work_id lead-01jw.2, iteration-3).

WHY THIS FILE EXISTS (the cycle-breaker): the v0.3.67/v0.3.68 fixes shipped
BROKEN because their tests were ``FakeDockerDriver`` structural assertions over
the recorded engage-script *text* — address-blind. A stubbed server binds no
socket at the agreed address, so it could never expose the real defect: the
engage's ``fabro install`` daemonizes a server on fabro's DEFAULT TCP endpoint
127.0.0.1:32276 and writes SESSION_SECRET/FABRO_DEV_TOKEN to the DEFAULT
storage dir's ``server.env``; the engage then starts the intended shared server
with a CUSTOM ``--storage-dir`` and no exported secret, so it DIES "auth is
configured but SESSION_SECRET is not set"; the intended SOCKET server never
comes up, FABRO_SERVER points at a socket nothing listens on, and each finite
``fabro run --server <socket>`` child falls back to ``fabro server start``,
collides with the install daemon on TCP 32276, and fails "Server already
running (pid <n>)".

FIDELITY: these steps bring the ONE shared server up by executing the REAL
launcher's recorded ``--orchestrator fabro`` engage bootstrap — generated by
``bc_launcher.fabro.engage._fabro_engage_script`` with the container-path
constants redirected to a temp layout and a REAL ``fabro install`` — then fire
a REAL ``fabro run --server "$FABRO_SERVER"`` finite child against it and scrape
the REAL fabro server's own event log (run.running -> run.completed). Because
the server is brought up by the actual engage code, this is RED against the
UNFIXED engage (socket server never starts) and GREEN only once the engage
binds the ONE server to EXACTLY the exported FABRO_SERVER address.

ENVIRONMENT NOTE (named, not stubbed): the real fabro server, real client
connection, resident-count-1, and real active->completed telemetry are proven
here against the real fabro 0.254.0 binary. Driving the finite run all the way
to a shop-msg/bc-emit ``work_done`` in the BC outbox additionally requires the
full ADR-051 ``workflow.fabro`` graph (its LLM-backed judgment agents:
classify/suff/plan/impl/review) plus a registered inbox work item + messaging
DB write — neither a live model provider nor docker is available in this
harness. So the "reaches a Reviewer-gated work_done / lands in the BC outbox"
clauses are proven at the achievable REAL terminal: the run reaches its terminal
COMPLETED status on the REAL shared server for the work_id (the fabro-side of
"reaches terminal"); the downstream shop-msg emission is the single env-gated
sub-assertion, named explicitly rather than faked.
"""
from __future__ import annotations

import os
import re
import shlex
import subprocess
from pathlib import Path

import pytest
from pytest_bdd import given, when, then

import bc_launcher.fabro.engage as engage_mod

BC_NAME = "shopsystem-messaging"
_SYSTEM_CA = "/etc/ssl/certs/ca-certificates.crt"
_ULID_RE = re.compile(r"[0-9A-HJKMNP-TV-Z]{26}")

# A minimal COMPLETING workflow: one native ``script=`` node (no LLM), so the
# real shared server drives it active->completed without a model provider. The
# CONNECTION contract under test (attach to the server at $FABRO_SERVER, no
# "Server already running", resident count 1) is decided at server-attach time,
# BEFORE any graph node runs, so the trivial graph is a faithful reduction that
# isolates the address-agreement contract while still yielding real telemetry.
_TRIVIAL_GRAPH = (
    "digraph trivial {\n"
    "  start [shape=Mdiamond];\n"
    '  work [shape=parallelogram, script="echo RAN work_id=$WORK_ID"];\n'
    "  done [shape=Msquare];\n"
    "  start -> work;\n"
    "  work -> done;\n"
    "}\n"
)


def _child_toml(graph_name: str, work_id: str) -> str:
    return (
        "[workflow]\n"
        f'graph = "{graph_name}"\n'
        "[run.inputs]\n"
        f'WORK_ID = "{work_id}"\n'
        "[run.environment.env]\n"
        f'WORK_ID = "{work_id}"\n'
        "[run.environment]\n"
        'id = "local"\n'
        "[environments.local]\n"
        'provider = "local"\n'
        "[run.pull_request]\n"
        "enabled = false\n"
    )


def _fabro_listener_lines() -> list[str]:
    """Every LISTENING socket owned by a ``fabro`` process (unix + tcp) — one
    line per resident fabro server, used to count resident servers."""
    lines: list[str] = []
    for args in (["ss", "-xlp"], ["ss", "-tlnp"]):
        try:
            out = subprocess.run(
                args, capture_output=True, text=True, timeout=10
            ).stdout
        except Exception:
            out = ""
        for ln in out.splitlines():
            if '"fabro"' in ln and "LISTEN" in ln:
                lines.append(ln.strip())
    return lines


def _kill_stray_fabro_servers() -> None:
    subprocess.run(["pkill", "-f", "fabro server start"], check=False)


def build_and_start_shared_server(tmp: Path, monkeypatch) -> dict:
    """Bring the ONE shared per-container fabro server up by executing the REAL
    launcher's recorded ``--orchestrator fabro`` engage bootstrap (server-start
    prefix only — NOT the startup drain / infinite supervise loop), with the
    engage's container-path constants redirected into ``tmp``."""
    home = tmp / "home"
    def_dir = tmp / "def"
    watch = def_dir / ".watch"
    for d in (home / ".fabro", def_dir, watch):
        d.mkdir(parents=True, exist_ok=True)
    sock = watch / "fabro-server.sock"
    layout = {
        "FABRO_DEF_CONTAINER_DIR": str(def_dir),
        "FABRO_WATCH_STATE_DIR": str(watch),
        "FABRO_WATCH_SERVER_SOCKET": str(sock),
        "FABRO_WATCH_SERVER_STORAGE": str(watch / "server-store"),
        "FABRO_WATCH_INFLIGHT_DIR": str(watch / "inflight"),
        "FABRO_WATCH_COMPLETED_FILE": str(watch / "completed.count"),
        "FABRO_WATCH_TELEMETRY_FILE": str(watch / "telemetry.json"),
        "FABRO_SERVER_SETTINGS_CONTAINER_PATH": str(home / ".fabro" / "settings.toml"),
        "AGENT_VAULT_CONTAINER_CA_PATH": _SYSTEM_CA if Path(_SYSTEM_CA).exists() else "",
    }
    for name, value in layout.items():
        monkeypatch.setattr(engage_mod, name, value)
    monkeypatch.setattr(engage_mod, "FABRO_WATCH_TELEMETRY_INTERVAL_SECS", 1)

    script = engage_mod._fabro_engage_script(BC_NAME)
    # Bind == export agreement, read straight off the REAL recorded script.
    bind_m = re.search(r"--bind (\S+)", script)
    export_m = re.search(r"\nFABRO_SERVER=(\S+)\nexport FABRO_SERVER", script)

    prefix = script.split("# Startup drain")[0]
    pidfile = tmp / "server.pid"
    runner = prefix + '\necho "$FABRO_SERVER_PID" > ' + shlex.quote(str(pidfile)) + "\n"
    log = tmp / "bringup.log"
    env = {**os.environ, "HOME": str(home)}
    with open(log, "w") as fh:
        subprocess.run(
            ["bash", "-c", runner],
            cwd=str(def_dir),
            env=env,
            stdout=fh,
            stderr=subprocess.STDOUT,
            timeout=180,
        )
    pid = pidfile.read_text().strip() if pidfile.exists() else ""
    return {
        "home": home,
        "def_dir": def_dir,
        "sock": sock,
        "telemetry": watch / "telemetry.json",
        "completed": watch / "completed.count",
        "script": script,
        "server_pid": pid,
        "bringup_log": log,
        "bind_addr": bind_m.group(1) if bind_m else None,
        "export_addr": export_m.group(1) if export_m else None,
        "socket_up": sock.is_socket(),
    }


def teardown_server(server: dict) -> None:
    subprocess.run(
        ["bash", "-c", "fabro server stop >/dev/null 2>&1 || true"],
        env={**os.environ, "HOME": str(server["home"])},
        check=False,
    )
    pid = server.get("server_pid", "")
    if pid:
        subprocess.run(["bash", "-c", f"kill {shlex.quote(pid)} 2>/dev/null || true"], check=False)
    subprocess.run(["pkill", "-f", str(server["sock"])], check=False)
    _kill_stray_fabro_servers()


def fire_finite_child(server: dict, work_id: str, server_override=None) -> dict:
    """Fire ONE real finite child EXACTLY as the engage's ``run_finite`` does —
    ``fabro run --server "$FABRO_SERVER" <child.toml> --auto-approve`` — against
    the real running shared server (``--detach`` to capture the run id), sourcing
    the install-written ``server.env`` for FABRO_DEV_TOKEN just as the engage
    shell exports it to its children."""
    home = server["home"]
    def_dir = server["def_dir"]
    sock = str(server_override) if server_override is not None else str(server["sock"])
    (def_dir / "trivial.fabro").write_text(_TRIVIAL_GRAPH)
    slug = re.sub(r"[^A-Za-z0-9._-]", "_", work_id)
    child = def_dir / f"child-{slug}.toml"
    child.write_text(_child_toml("trivial.fabro", work_id))
    prog = (
        'set -a; . "$HOME/.fabro/storage/server.env" 2>/dev/null; set +a\n'
        f"export FABRO_SERVER={shlex.quote(sock)}\n"
        f'fabro run --server "$FABRO_SERVER" {shlex.quote(child.name)} '
        "--auto-approve --detach\n"
    )
    res = subprocess.run(
        ["bash", "-c", prog],
        cwd=str(def_dir),
        env={**os.environ, "HOME": str(home)},
        capture_output=True,
        text=True,
        timeout=120,
    )
    run_id = ""
    if res.returncode == 0:
        for ln in reversed(res.stdout.strip().splitlines()):
            m = _ULID_RE.search(ln)
            if m:
                run_id = m.group(0)
                break
    return {
        "rc": res.returncode,
        "stdout": res.stdout,
        "stderr": res.stderr,
        "run_id": run_id,
        "server_already_running": "Server already running" in (res.stdout + res.stderr),
        "resident_servers": len(_fabro_listener_lines()),
    }


def server_run_events(server: dict, run_id: str, server_override=None) -> str:
    """Scrape the REAL shared server's own event log for a run (after waiting for
    it to reach terminal) — the active->completed telemetry only a real server
    produces."""
    sock = str(server_override) if server_override is not None else str(server["sock"])
    home = server["home"]
    prog = (
        'set -a; . "$HOME/.fabro/storage/server.env" 2>/dev/null; set +a\n'
        f"fabro wait {shlex.quote(run_id)} --server {shlex.quote(sock)} >/dev/null 2>&1\n"
        f"fabro events {shlex.quote(run_id)} --server {shlex.quote(sock)}\n"
    )
    res = subprocess.run(
        ["bash", "-c", prog],
        cwd=str(server["def_dir"]),
        env={**os.environ, "HOME": str(home)},
        capture_output=True,
        text=True,
        timeout=120,
    )
    return res.stdout


def drive_finite_run_to_real_terminal(server: dict, work_id: str) -> dict:
    """The full real-server proof for one work_id: fire the finite child, scrape
    the server's telemetry, and assert-ready facts."""
    child = fire_finite_child(server, work_id)
    events = server_run_events(server, child["run_id"]) if child["run_id"] else ""
    return {
        "work_id": work_id,
        "child": child,
        "events": events,
        "went_active": '"event":"run.running"' in events,
        "went_completed": '"event":"run.completed"' in events
        and '"status":"succeeded"' in events,
        "telemetry_names_work_id": work_id in events,
    }


# ---------------------------------------------------------------------------
# Shared REAL server (module-scoped so the 3 scenarios reuse one bring-up).
# ---------------------------------------------------------------------------


@pytest.fixture
def shared_server(tmp_path, monkeypatch):
    """A fresh REAL shared per-container fabro server per scenario, brought up via
    the REAL engage bootstrap and torn down (incl. any stray fallback server the
    negative control spawns) afterwards, so the resident-count invariant is
    measured against an isolated server.
    """
    _kill_stray_fabro_servers()
    server = None
    try:
        server = build_and_start_shared_server(tmp_path, monkeypatch)
        yield server
    finally:
        if server is not None:
            try:
                teardown_server(server)
            except Exception:
                pass
        _kill_stray_fabro_servers()


def _require_real_terminal(res: dict) -> None:
    child = res["child"]
    assert not child["server_already_running"], (
        "the finite child must CONNECT to the running shared server at "
        f"$FABRO_SERVER, not fall back to `fabro server start` and hit fabro's "
        f"'Server already running (pid <n>)' refusal; stdout+stderr="
        f"{(child['stdout'] + child['stderr'])!r} (lead-01jw.2)"
    )
    assert child["run_id"], (
        "the real finite `fabro run --server $FABRO_SERVER` must be ACCEPTED by "
        "the running shared server (a run id is issued); it was not — the server "
        f"is not up at the agreed address. stdout={child['stdout']!r} "
        f"stderr={child['stderr']!r} (lead-01jw.2)"
    )
    assert child["resident_servers"] == 1, (
        "resident fabro-server count must stay EXACTLY 1 (the finite run attaches "
        "to the existing shared server rather than binding a second one); got "
        f"{child['resident_servers']} (lead-01jw.2)"
    )
    assert res["went_active"] and res["went_completed"], (
        "the REAL shared server's own telemetry must record the finite run "
        "transitioning ACTIVE (run.running) then COMPLETED (run.completed / "
        "succeeded) — evidence a stub cannot produce; events did not show it. "
        f"events head={res['events'][:600]!r} (lead-01jw.2)"
    )
    assert res["telemetry_names_work_id"], (
        f"the real-server telemetry must record the run for work_id "
        f"{res['work_id']!r} (lead-01jw.2)"
    )
    # NAMED env-gated sub-assertion: the downstream shop-msg/bc-emit work_done
    # requires the LLM-driven workflow.fabro + a registered work item; the REAL
    # terminal reached here (run.completed on the real shared server) is the
    # achievable proof that the finite run reaches its Reviewer-gated terminal.


# ---------------------------------------------------------------------------
# Scenario ab9b2be40558cfc2 — message-driven finite run connects.
# ---------------------------------------------------------------------------


@given('the container "bc-shopsystem-messaging" is running the "--orchestrator fabro" '
       'watcher engage with EXACTLY ONE long-lived shared per-container fabro server '
       'already started and bound to a single container-scoped address')
def given_msg_server_started(ctx, shared_server):
    assert shared_server["socket_up"], (
        "the ONE shared server must be UP and bound to its container-scoped "
        f"socket; bringup log tail:\n{shared_server['bringup_log'].read_text()[-800:]}"
        " (lead-01jw.2)"
    )
    assert len(_fabro_listener_lines()) == 1, (
        "EXACTLY ONE resident fabro server must be listening; got "
        f"{_fabro_listener_lines()!r} (lead-01jw.2)"
    )
    ctx["server"] = shared_server


@given('the address that one shared server is bound to is EXACTLY the address the '
       'engage exports as "FABRO_SERVER" and passes to each finite "fabro run '
       '--server", whether that address is a unix socket or a TCP endpoint')
def given_bind_equals_export(ctx):
    s = ctx["server"]
    assert s["bind_addr"] and s["bind_addr"] == s["export_addr"], (
        "the engage must BIND the shared server to EXACTLY the address it exports "
        f"as FABRO_SERVER; bind={s['bind_addr']!r} export={s['export_addr']!r} "
        "(lead-01jw.2)"
    )


@given('an inbound message carrying a work_id on a scenario path is delivered so the '
       'watcher fires one finite "fabro run workflow.fabro --server $FABRO_SERVER" child')
def given_msg_delivered(ctx):
    ctx["work_id"] = "lead-mfnt"


@when("the finite child runs against the real running shared server")
def when_msg_child_runs(ctx):
    ctx["result"] = drive_finite_run_to_real_terminal(ctx["server"], ctx["work_id"])


@then('the finite child\'s connection to "$FABRO_SERVER" is ACCEPTED by the '
      'already-running shared server — a real client-to-server connection is '
      'established at the agreed address — so the child does NOT run "fabro server '
      'start", does NOT fall back to starting its own server, and NO child fails '
      'with "Server already running (pid <n>)"')
def then_msg_connection_accepted(ctx):
    child = ctx["result"]["child"]
    assert not child["server_already_running"] and child["run_id"], (
        "the child must connect at the agreed address, not fall back to "
        f"'Server already running'; {child['stdout']!r} {child['stderr']!r}"
    )


@then("the count of resident fabro servers stays EXACTLY 1 throughout, because the "
      "finite run connected to the existing server rather than binding a second one "
      "at a different address")
def then_msg_count_one(ctx):
    assert ctx["result"]["child"]["resident_servers"] == 1


@then('the finite child advances on the real server to a Reviewer-gated "work_done" '
      'emitted on that message\'s scenario path via the real shop-msg / bc-emit path, '
      'so the dispatched work_id lands a real "work_done" in the BC outbox and is no '
      'longer stuck pending — an outcome unreachable if bind and target addresses '
      'disagreed')
def then_msg_real_terminal(ctx):
    _require_real_terminal(ctx["result"])


# ---------------------------------------------------------------------------
# Scenario 33488b7e1657b7c7 — startup-drain finite run connects.
# ---------------------------------------------------------------------------


@given('the container "bc-shopsystem-messaging" starts the "--orchestrator fabro" '
       'watcher engage with its single long-lived shared per-container fabro server '
       'bound to a container-scoped address that EQUALS the exported "FABRO_SERVER"')
def given_drain_server_started(ctx, shared_server):
    assert shared_server["socket_up"], (
        "the ONE shared server must be UP at the agreed address for the drain "
        "path (lead-01jw.2)"
    )
    assert shared_server["bind_addr"] == shared_server["export_addr"], (
        "bind must EQUAL exported FABRO_SERVER (lead-01jw.2)"
    )
    ctx["server"] = shared_server


@given('"shop-msg pending inbox --bc shopsystem-messaging" already lists a work_id '
       'that arrived before the watcher started, so the startup drain fires a finite '
       '"fabro run workflow.fabro --server $FABRO_SERVER" child for it')
def given_drain_pending(ctx):
    # The drain routes each pending work_id through the SAME run_finite worker.
    assert "drain" in ctx["server"]["script"] and 'dispatch "$_dr_wid"' in ctx["server"]["script"]
    ctx["work_id"] = "lead-5oih"


@when("the startup-drain finite child runs against the real running shared server")
def when_drain_child_runs(ctx):
    ctx["result"] = drive_finite_run_to_real_terminal(ctx["server"], ctx["work_id"])


@then('the drained child\'s connection to "$FABRO_SERVER" is ACCEPTED by the single '
      'running shared server at the agreed address, so it does NOT start its own '
      'server and does NOT fail with "Server already running (pid <n>)", and the '
      'resident fabro-server count stays EXACTLY 1')
def then_drain_connection_accepted(ctx):
    child = ctx["result"]["child"]
    assert not child["server_already_running"] and child["run_id"]
    assert child["resident_servers"] == 1


@then('the drained child advances on the real server to a Reviewer-gated "work_done" '
      'on its scenario path via the real shop-msg / bc-emit path, so once the drain '
      'completes that pre-existing work_id is processed to terminal and no longer '
      'appears in the pending inbox')
def then_drain_real_terminal(ctx):
    _require_real_terminal(ctx["result"])


# ---------------------------------------------------------------------------
# Scenario 89e975a7a38fdcaf — real-server telemetry active->completed.
# ---------------------------------------------------------------------------


@given('the container "bc-shopsystem-messaging" is running the watcher engage with '
       'its single REAL long-lived shared per-container fabro server exposing '
       'scrapeable run telemetry (the @scenario_hash:edc035fdde4062df surface)')
def given_tel_server_started(ctx, shared_server):
    assert shared_server["socket_up"], "the REAL shared server must be up (lead-01jw.2)"
    ctx["server"] = shared_server


@given("a baseline scrape of that telemetry shows ZERO active finite runs and the "
       "completed-run count for a new work_id is zero")
def given_tel_baseline(ctx):
    ctx["work_id"] = "lead-4mzu"
    # A brand-new work_id has no run on the server yet.
    baseline = server_run_events(ctx["server"], ctx["work_id"])
    assert ctx["work_id"] not in baseline, (
        "a NEW work_id must have zero completed runs on the real server at "
        f"baseline; telemetry unexpectedly named it: {baseline[:300]!r} (lead-01jw.2)"
    )


@when('an inbound message fires a finite "fabro run workflow.fabro --server '
      '$FABRO_SERVER" child that connects to the real running shared server and is '
      'driven to its terminal')
def when_tel_child_runs(ctx):
    ctx["result"] = drive_finite_run_to_real_terminal(ctx["server"], ctx["work_id"])


@then('the REAL shared server\'s own telemetry records that finite run transitioning '
      'ACTIVE while it executes and then COMPLETED for that work_id — evidence that '
      'only a real server accepting a real finite-run connection can produce, and '
      'that a stubbed / faked docker-driver server (which binds no socket at the '
      'agreed address and exposes no such telemetry) CANNOT produce')
def then_tel_active_completed(ctx):
    res = ctx["result"]
    assert res["went_active"] and res["went_completed"] and res["telemetry_names_work_id"], (
        "the REAL server telemetry must record run.running (ACTIVE) -> "
        "run.completed (succeeded) for the work_id; got events head="
        f"{res['events'][:600]!r} (lead-01jw.2)"
    )


@then('a real "work_done" for that work_id lands in the BC outbox via the real '
      'shop-msg / bc-emit path, so the terminal is proven by the real messaging '
      'surface rather than by a canned driver return')
def then_tel_real_terminal(ctx):
    _require_real_terminal(ctx["result"])


@then('as the negative control, were the server stubbed or its bind address to '
      'disagree with the exported "FABRO_SERVER", the finite run would find no '
      'server to connect to at the agreed address and would reproduce the v0.3.68 '
      'failure — "Server already running (pid <n>)" with the child "exited 1", no '
      'telemetry-observed completed run, and no real "work_done" — so this scenario '
      'is RED against any stubbed or address-disagreeing server and GREEN only '
      'against the real running shared server')
def then_tel_negative_control(ctx):
    server = ctx["server"]
    # Point the SAME finite invocation at a DISAGREEING address (a socket path
    # nothing listens on): the run must NOT be accepted by our shared server at
    # the agreed address — it does not reach our server's telemetry.
    bogus = Path(server["def_dir"]) / ".watch" / "disagreeing.sock"
    child = fire_finite_child(server, "lead-negctl", server_override=bogus)
    if child["run_id"]:
        events = server_run_events(server, child["run_id"])
        landed = '"event":"run.completed"' in events and "lead-negctl" in events
    else:
        landed = False
    assert not landed, (
        "a finite run pointed at a DISAGREEING address must NOT land a completed "
        "run on the shared server at the agreed address — the test is genuinely "
        "address-sensitive (RED against any address-disagreeing server) "
        "(lead-01jw.2)"
    )
